# config for List<String>
my:
 servers:
  - dev.bar.com
  - foo.bar.com

# config for Map<String, Person>
personMap: # prefix
 persons: # POJO's field
  Tom: # Map's key
   name: Tom
   age: 12
   sex: man
   salary: 1000.25
   # 不要设置为isOld，因为Person的setter函数为：setOld()/setold(),如果要使用isOld，需要显示的声明 setIsOld
   old: false
   birthDay: 1995-10-11 12:45:15
   address: # list方式1，每个元素前面都添加“-”
    - Beijing
    - Nanjing
   books: # list<Book> books;
    - name: Java并发编程实战
      auther: AutherJava
      category: java
    - name: 深入理解Mysql
      auther: AutherMysql
      category: mysql
   maps: {key1: value1, key2: value2, key3: value3}  # Map<String, String>
  July: # Map's key
   name: July
   age: 15
   sex: woman
   salary: 120.25
   address: # list方式2，仅在第一个元素前面都添加“-”
    - Shanghai
      Nanjing
  Jame:  # Map's key
   name: jame
   age: 35
   sex: man
   Old: true
   address: Suzhou,Xuzhou # list方式3：元素以逗号分隔
   birthDay: 1975-7-8 08:45:15

